create table if not exists audit_trails (
    id bigint generated by default as identity primary key,
    merchant_id bigint not null
        references merchant_products(id)
        on delete cascade,
    audit_json jsonb not null,
    created_at timestamptz default now()
);

create index if not exists idx_audit_trails_merchant_id
on audit_trails(merchant_id);