create table if not exists score_reports (
    id bigint generated by default as identity primary key,
    merchant_id bigint not null
        references merchant_products(id)
        on delete cascade,
    score_json jsonb not null,
    created_at timestamptz default now()
);

create index if not exists idx_score_reports_merchant_id
on score_reports(merchant_id);